[workspace]
resolver = "2"

members = ["day-*"]
default-members = ["day-*"]

[workspace.dependencies]
itertools = "0.12.0"
nom = "7.1.3"
rayon = "1.8.0"
divan = "0.1.5"
regex = "1.10.2"
roots = "0.0.8"
criterion = { version = "0.5.1", features = ["html_reports"] }
