name: Continuous Integration

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Z3
        run: sudo apt-get install libz3-dev -y
        continue-on-error: true
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: cargo check
        run: cargo check
      - name: cargo test
        run: cargo test
      - name: cargo clippy
        run: cargo clippy -- -D warnings
      - name: cargo fmt
        run: cargo fmt --check
